import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Search, UserCheck, X, XCircle } from 'lucide-react'
import { api } from '../api'
import type { User } from '../types'
import { faNumber, formatJalali, formatJalaliDateTime } from '../utils/jalali'

type Payment={id:string;plan_name:string;amount:number;status:string;created_at:string}
type Sub={id:string;plan_name:string;starts_at:string;expires_at:string;status:string}
type Detail=User&{created_at:string;profile?:Record<string,unknown>|null;advisor?:User|null;assignment?:{approval_status:string;active:boolean}|null;payments:Payment[];subscriptions:Sub[]}
const labels:Record<string,string>={active:'فعال',suspended:'غیرفعال',pending_payment:'در انتظار پرداخت',pending_approval:'در انتظار تأیید',pending_assignment:'در انتظار تخصیص',approved:'تأییدشده',rejected:'ردشده',paid:'پرداخت‌شده',pending:'در انتظار پرداخت',pending_activation:'در انتظار فعال‌سازی'}
const roles:Record<string,string>={student:'دانش‌آموز',advisor:'مشاور',secretary:'منشی',upper_secondary_manager:'مسئول متوسطه دوم',lower_secondary_manager:'مسئول متوسطه اول',finance:'مدیر مالی',operations_admin:'مدیر عملیات',super_admin:'مدیر سایت',support:'پشتیبان',content_editor:'کارشناس محتوا',reviewer:'بازبین',exam_designer:'طراح آزمون'}
const fieldLabels:Record<string,string>={education_level:'مقطع',grade:'پایه',major:'رشته',school:'مدرسه',goal:'هدف',national_code:'کد ملی',birth_date:'تاریخ تولد',parent_name:'نام ولی',parent_phone:'موبایل ولی',address:'نشانی',education_degree:'مدرک تحصیلی',education_field:'رشته تحصیلی',experience_years:'سابقه کار',bio:'معرفی و سابقه',support_capacity:'ظرفیت',academic_year:'سال تحصیلی',approval_status:'تأیید کلی',lead_approval_status:'تأیید مسئول مقطع',admin_approval_status:'تأیید مدیر',advisor_approval_status:'تأیید مشاور',registration_review_status:'وضعیت بررسی اطلاعات',registration_review_note:'علت رد/توضیح',approval_note:'توضیح تأیید',advisor_selection_mode:'روش انتخاب مشاور'}
export default function AdminUserDirectoryPage(){
 const qc=useQueryClient(),[search,setSearch]=useState(''),[role,setRole]=useState('all'),[selectedId,setSelectedId]=useState(''),[note,setNote]=useState('')
 const users=useQuery({queryKey:['admin-users'],queryFn:()=>api<(User&{created_at:string})[]>('/admin/users')})
 const detail=useQuery({queryKey:['admin-user-detail',selectedId],queryFn:()=>api<Detail>('/admin/users/'+selectedId+'/detail'),enabled:Boolean(selectedId)})
 const update=useMutation({mutationFn:({id,status}:{id:string;status:string})=>api('/admin/users/'+id+'/status',{method:'PATCH',body:JSON.stringify({status})}),onSuccess:()=>qc.invalidateQueries({queryKey:['admin-users']})})
 const approve=useMutation({mutationFn:({status,asAdvisor}:{status:'approved'|'rejected';asAdvisor:boolean})=>api('/admin/students/'+selectedId+'/registration-approval',{method:'PATCH',body:JSON.stringify({status,note,approve_as_advisor:asAdvisor})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['admin-user-detail',selectedId]});qc.invalidateQueries({queryKey:['admin-users']})}})
 const rows=useMemo(()=>(users.data||[]).filter(item=>(role==='all'||item.role===role)&&(item.full_name.includes(search)||item.phone.includes(search))),[users.data,search,role])
 if(users.isLoading)return <div className="page-state">در حال دریافت کاربران...</div>
 function show(value:unknown){if(value===null||value===undefined||value==='')return '—';if(typeof value==='object')return Array.isArray(value)?faNumber(value.length)+' مورد':Object.entries(value as Record<string,unknown>).map(([key,item])=>key+': '+String(item||'—')).join(' | ');return String(value)}
 return <div className="content-page"><div className="section-head"><div><h1>مدیریت کاربران</h1><p>با انتخاب نام هر شخص، تمام اطلاعات ثبت‌نام، پرداخت و اشتراک در پنجره جزئیات نمایش داده می‌شود.</p></div></div><div className="admin-toolbar"><div className="list-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام یا شماره موبایل..."/></div><select value={role} onChange={e=>setRole(e.target.value)}><option value="all">همه نقش‌ها</option>{Object.entries(roles).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></div><div className="admin-table"><div className="admin-table-head"><span>کاربر</span><span>نقش</span><span>وضعیت</span><span>شماره</span><span>دسترسی</span></div>{rows.map(item=><div className="admin-table-row" key={item.id}><button className="user-detail-link" onClick={()=>setSelectedId(item.id)}><i className="avatar">{item.full_name[0]}</i><b>{item.full_name}</b></button><span>{roles[item.role]||item.role}</span><span>{labels[item.status]||item.status}</span><span dir="ltr">{item.phone}</span><select value={item.status} onChange={e=>update.mutate({id:item.id,status:e.target.value})}><option value="active">فعال</option><option value="suspended">غیرفعال</option><option value="pending_approval">در انتظار تأیید</option></select></div>)}</div>
 {selectedId&&<div className="user-detail-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedId('')}}><section className="user-detail-modal"><button className="detail-close" onClick={()=>setSelectedId('')}><X/></button>{detail.isLoading?<div className="page-state">در حال دریافت پرونده...</div>:detail.data?<><header><span className="avatar">{detail.data.full_name[0]}</span><div><h2>{detail.data.full_name}</h2><p>{roles[detail.data.role]||detail.data.role} · {detail.data.phone} · ثبت‌نام {formatJalali(detail.data.created_at)}</p></div></header><div className="detail-grid"><p><small>وضعیت حساب</small><b>{labels[detail.data.status]||detail.data.status}</b></p><p><small>مشاور مرتبط</small><b>{detail.data.advisor?.full_name||'ندارد'}</b></p>{Object.entries(detail.data.profile||{}).filter(([key])=>!['documents','school_schedule','extra_classes'].includes(key)).map(([key,value])=><p key={key}><small>{fieldLabels[key]||key}</small><b>{show(value)}</b></p>)}</div>{detail.data.profile?.school_schedule&&<section><h3>برنامه مدرسه و کلاس‌ها</h3><p className="json-summary">{show(detail.data.profile.school_schedule)}</p><p className="json-summary">{show(detail.data.profile.extra_classes)}</p></section>}<section><h3>وضعیت اشتراک</h3>{detail.data.subscriptions.map(item=><div className="detail-row" key={item.id}><b>{item.plan_name}</b><span>{formatJalali(item.starts_at)} تا {formatJalali(item.expires_at)}</span><em>{labels[item.status]||item.status}</em></div>)}{!detail.data.subscriptions.length&&<p>اشتراکی ثبت نشده است.</p>}</section><section><h3>پرداخت‌ها</h3>{detail.data.payments.map(item=><div className="detail-row" key={item.id}><b>{faNumber(item.amount.toLocaleString('en-US'))} تومان</b><span>{item.plan_name} · {formatJalaliDateTime(item.created_at)}</span><em>{labels[item.status]||item.status}</em></div>)}{!detail.data.payments.length&&<p>پرداختی ثبت نشده است.</p>}</section>{detail.data.role==='student'&&<section className="approval-actions"><h3><UserCheck/> تأیید ثبت‌نام دانش‌آموز</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="توضیح یا علت رد پرونده..."/><div><button onClick={()=>approve.mutate({status:'approved',asAdvisor:false})}><CheckCircle2/> تأیید مدیر</button><button onClick={()=>approve.mutate({status:'approved',asAdvisor:true})}><CheckCircle2/> تأیید مدیر و به‌جای مشاور</button><button className="danger" disabled={!note.trim()} onClick={()=>approve.mutate({status:'rejected',asAdvisor:false})}><XCircle/> رد با دلیل</button></div></section>}</>:<div className="error-box">دریافت جزئیات ناموفق بود.</div>}</section></div>}
 </div>
}
