import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BellRing, Check, FilePenLine, Plus, Send, X } from 'lucide-react'
import { useState } from 'react'
import { api } from '../api'
import '../styles/public-content.css'
import '../styles/article-management-fix.css'

type Article={id:string;title:string;body:string;status:string;author_name:string;author_role:string;created_at:string}
const labels:Record<string,string>={pending:'در انتظار تأیید',approved:'منتشرشده',rejected:'ردشده'}
export function ArticlesManagementPage({admin=false}:{admin?:boolean}){const qc=useQueryClient();const {data=[]}=useQuery({queryKey:['managed-articles',admin],queryFn:()=>api<Article[]>('/articles/mine')});const [editing,setEditing]=useState<Article|null>(null);const [title,setTitle]=useState('');const [body,setBody]=useState('');const save=useMutation({mutationFn:()=>api(editing?`/articles/${editing.id}`:'/articles',{method:editing?'PUT':'POST',body:JSON.stringify({title,body})}),onSuccess:()=>{setTitle('');setBody('');setEditing(null);qc.invalidateQueries({queryKey:['managed-articles']})}});const review=useMutation({mutationFn:({id,status}:{id:string;status:string})=>api(`/admin/articles/${id}/review`,{method:'POST',body:JSON.stringify({status})}),onSuccess:()=>qc.invalidateQueries({queryKey:['managed-articles']})});function edit(item:Article){setEditing(item);setTitle(item.title);setBody(item.body);window.scrollTo({top:0,behavior:'smooth'})}return <div className="content-page"><div className="page-head"><div><h1>مقالات</h1><p>{admin?'مقاله جدید منتشر کنید یا نوشته‌های مشاوران را ویرایش و تأیید کنید.':'مقاله‌های آموزشی خود را ثبت کنید؛ نوشته پس از تأیید مدیر منتشر می‌شود.'}</p></div></div><section className="panel content-editor"><h2>{editing?'ویرایش مقاله':'افزودن مقاله جدید'}</h2><label>عنوان مقاله<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={180}/></label><label>متن مقاله<textarea value={body} onChange={e=>setBody(e.target.value)} rows={10}/></label><div><button className="btn btn-primary" disabled={title.trim().length<3||body.trim().length<20||save.isPending} onClick={()=>save.mutate()}>{editing?<FilePenLine/>:<Plus/>}{editing?'ذخیره ویرایش':'ثبت مقاله'}</button>{editing&&<button className="btn btn-outline" onClick={()=>{setEditing(null);setTitle('');setBody('')}}>انصراف</button>}</div></section><div className="managed-articles">{data.map(item=><article className="panel" key={item.id}><div><span className={'article-status '+item.status}>{labels[item.status]||item.status}</span><h3>{item.title}</h3><small>نویسنده: {item.author_name}</small></div><p>{item.body}</p><div className="article-actions"><button className="btn btn-outline" onClick={()=>edit(item)}><FilePenLine/>ویرایش</button>{admin&&item.status!=='approved'&&<button className="btn btn-primary" onClick={()=>review.mutate({id:item.id,status:'approved'})}><Check/>تأیید و انتشار</button>}{admin&&item.status!=='rejected'&&<button className="btn btn-danger" onClick={()=>review.mutate({id:item.id,status:'rejected'})}><X/>رد مقاله</button>}</div></article>)}</div></div>}

export function AdminBroadcastPage(){const [audience,setAudience]=useState('all'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[sent,setSent]=useState<number|null>(null);const send=useMutation({mutationFn:()=>api<{delivered:number}>('/admin/notifications/broadcast',{method:'POST',body:JSON.stringify({audience,title,body})}),onSuccess:r=>{setSent(r.delivered);setTitle('');setBody('')}});return <div className="content-page"><div className="page-head"><div><h1>ارسال اعلان</h1><p>پیام مدیر در زنگوله کاربران انتخاب‌شده نمایش داده می‌شود.</p></div></div><section className="panel content-editor"><h2><BellRing/> اعلان جدید</h2><label>گیرندگان<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="students">همه دانش‌آموزان</option><option value="advisors">همه مشاوران</option><option value="all">همه کاربران</option></select></label><label>عنوان<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/></label><label>متن پیام<textarea value={body} onChange={e=>setBody(e.target.value)} rows={6}/></label><button className="btn btn-primary" disabled={title.trim().length<2||body.trim().length<2||send.isPending} onClick={()=>send.mutate()}><Send/>ارسال اعلان</button>{sent!==null&&<p className="success-note">اعلان برای {sent.toLocaleString('fa-IR')} کاربر ارسال شد.</p>}{send.error&&<p className="form-error">{send.error.message}</p>}</section></div>}
