import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Download, MessageSquare, Printer, Search, ShieldCheck, UserPlus, XCircle } from 'lucide-react'
import { api } from '../api'
import type { AdminAdvisor, Message, Profile, User, WeeklyPlan } from '../types'
import { ChatPanel } from './OperationalPages'

const roleNames:Record<string,string>={secretary:'منشی',upper_secondary_manager:'مسئول متوسطه دوم',lower_secondary_manager:'مسئول متوسطه اول',advisor:'مشاور',student:'دانش‌آموز',super_admin:'مدیر سایت'}
function Head({title,text}:{title:string;text:string}){return <div className="section-head"><div><h1>{title}</h1><p>{text}</p></div></div>}
function State({text='در حال دریافت اطلاعات...'}:{text?:string}){return <div className="page-state">{text}</div>}
function ErrorBox({error}:{error:unknown}){return <div className="error-box">{error instanceof Error?error.message:'خطایی رخ داد'}</div>}
function StudentProfileDetails({student,profile}:{student:User;profile:Profile}){const schedule=profile.school_schedule||{},extras=profile.extra_classes||{};const averages=[['هفتم',profile.average_grade7],['هشتم',profile.average_grade8],['نهم',profile.average_grade9],['دهم',profile.average_grade10],['یازدهم',profile.average_grade11],['دوازدهم',profile.average_grade12]].filter(([,value])=>value!==null&&value!==undefined);return <div className="student-full-profile"><h2>اطلاعات کامل {student.full_name}</h2><div className="detail-grid"><Info label="شماره موبایل" value={student.phone}/><Info label="کد ملی" value={profile.national_code}/><Info label="تاریخ تولد" value={profile.birth_date}/><Info label="نام ولی" value={profile.parent_name}/><Info label="موبایل ولی" value={profile.parent_phone}/><Info label="نشانی" value={profile.address}/><Info label="پایه" value={profile.grade}/><Info label="رشته" value={profile.major||'نیاز ندارد'}/><Info label="مدرسه" value={profile.school}/><Info label="هدف تحصیلی" value={profile.goal||'ثبت نشده'}/><Info label="معدل‌های ثبت‌شده" value={averages.length?averages.map(([grade,value])=>`${grade}: ${value}`).join(' | '):'بدون معدل موردنیاز'}/></div>{Object.keys(schedule).length>0&&<section className="school-schedule-view"><h3>برنامه مدرسه و کلاس‌های فوق‌العاده</h3><div>{Object.entries(schedule).map(([day,periods])=><article key={day}><b>{day}</b>{periods.map((item,index)=><span key={index}>زنگ {index+1}: {item}</span>)}<small>{extras[day]||'بدون کلاس فوق‌العاده'}</small></article>)}</div></section>}</div>}
function Info({label,value}:{label:string;value:unknown}){return <p><small>{label}</small><b>{String(value||'—')}</b></p>}



export function ProgramsAccessPage({user}:{user:User}){
  const [search,setSearch]=useState('');const {data:plans=[],isLoading,error}=useQuery({queryKey:['management-plans'],queryFn:()=>api<WeeklyPlan[]>('/plans')});const {data:students=[]}=useQuery({queryKey:['management-students'],queryFn:()=>api<(User&{profile:Profile;advisor?:User})[]>('/management/students')})
  const names=Object.fromEntries(students.map(item=>[item.id,item.full_name]));const rows=useMemo(()=>plans.filter(plan=>(names[plan.student_id]||'').includes(search)||plan.week_label.includes(search)||plan.title.includes(search)),[plans,names,search])
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>
  return <div className="content-page"><Head title="برنامه‌های دانش‌آموزان" text="مشاهده و چاپ برنامه‌های مجاز بر اساس سطح دسترسی"/>{user.role!=='secretary'&&<StudentRegistrationReviews students={students}/>}<div className="list-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام دانش‌آموز یا هفته..."/></div><div className="management-plan-list">{rows.map(plan=><article className="panel" key={plan.id}><div><b>{names[plan.student_id]||'دانش‌آموز'}</b><h3>{plan.title}</h3><p>{plan.week_label} · نسخه {plan.version} · {plan.status==='published'?'منتشرشده':'پیش‌نویس'}</p></div><button className="btn btn-soft" onClick={()=>printPlan(plan,names[plan.student_id])}><Printer/> چاپ برنامه</button></article>)}</div>{!rows.length&&<State text="برنامه‌ای در این حوزه ثبت نشده است."/>}</div>
}

function StudentRegistrationReviews({students}:{students:(User&{profile:Profile})[]}){
  const qc=useQueryClient();const [selected,setSelected]=useState<(User&{profile:Profile})>();const review=useMutation({mutationFn:({id,note}:{id:string;note:string})=>api(`/management/students/${id}/review`,{method:'PATCH',body:JSON.stringify({status:'rejected',note})}),onSuccess:()=>qc.invalidateQueries({queryKey:['management-students']})})
  function reject(student:User){const note=window.prompt(`دلیل رد یا موارد نیازمند اصلاح برای ${student.full_name}:`,'');if(note?.trim())review.mutate({id:student.id,note:note.trim()})}
  return <section className="panel student-registration-reviews"><h2>بررسی اطلاعات ثبت‌نام دانش‌آموزان</h2><p>پیش از تصمیم‌گیری می‌توانید همه اطلاعات فردی، تحصیلی، معدل‌ها و برنامه مدرسه را ببینید.</p><div>{students.map(student=><article key={student.id}><span><b>{student.full_name}</b><small>{student.profile.grade} · {student.profile.school}</small></span><em>{student.profile.registration_review_status==='rejected'?'در انتظار اصلاح':'قابل بررسی'}</em><button className="btn btn-soft" onClick={()=>setSelected(student)}>مشاهده اطلاعات کامل</button><button className="btn btn-soft" disabled={review.isPending} onClick={()=>reject(student)}><XCircle/> رد و درخواست اصلاح</button></article>)}</div>{selected&&<section className="student-review-detail"><button className="detail-close" onClick={()=>setSelected(undefined)}><XCircle/></button><StudentProfileDetails student={selected} profile={selected.profile}/></section>}{review.error&&<ErrorBox error={review.error}/>}</section>
}

function printPlan(plan:WeeklyPlan,studentName='دانش‌آموز'){
  const popup=window.open('','_blank','width=1100,height=800');if(!popup)return
  const rows=plan.activities.map(item=>`<tr><td>${item.day}</td><td>${item.start_time} تا ${item.end_time}</td><td>${item.title}</td></tr>`).join('')
  popup.document.write(`<html dir="rtl"><head><title>${plan.title}</title><style>body{font-family:Tahoma;padding:30px}h1{text-align:center}table{width:100%;border-collapse:collapse}td,th{border:1px solid #333;padding:12px;text-align:center}@media print{button{display:none}}</style></head><body><h1>برنامه ${studentName}</h1><h2>${plan.week_label}</h2><p><b>ماموریت هفته:</b> ${plan.weekly_mission||'—'}</p><table><thead><tr><th>روز</th><th>ساعت</th><th>برنامه</th></tr></thead><tbody>${rows}</tbody></table><button onclick="window.print()">چاپ</button><script>window.onload=()=>window.print()</script></body></html>`);popup.document.close()
}

export function StaffMessagesPage({user}:{user:User}){
  const [selected,setSelected]=useState<User>();const {data=[],isLoading,error}=useQuery({queryKey:['management-contacts'],queryFn:()=>api<User[]>('/management/contacts')});const {data:alerts}=useQuery({queryKey:['notification-summary'],queryFn:()=>api<{unread_by_sender:Record<string,number>}>('/notifications/summary'),refetchInterval:5000})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>
  return <div className="content-page"><Head title="پیام‌ها" text="ارتباط مستقیم با اعضای مجاز مجموعه"/><div className="messages-layout"><aside>{data.map(item=><button className={selected?.id===item.id?'active':''} key={item.id} onClick={()=>setSelected(item)}><span className="avatar">{item.full_name[0]}</span><div><b>{item.full_name}</b><small>{roleNames[item.role]||item.role}</small></div>{!!alerts?.unread_by_sender[item.id]&&<i className="conversation-alert-dot"/>}</button>)}</aside><main>{selected?<ChatPanel counterpart={selected} currentUser={user}/>:<State text="یک مخاطب را انتخاب کنید."/>}</main></div></div>
}

type Conversation={student:User;advisor:User;last_message?:string;last_message_at?:string}
export function ConversationMonitorPage(){
  const [selected,setSelected]=useState<Conversation>();const {data=[],isLoading,error}=useQuery({queryKey:['management-conversations'],queryFn:()=>api<Conversation[]>('/management/conversations')});const {data:messages=[]}=useQuery({queryKey:['management-messages',selected?.student.id,selected?.advisor.id],queryFn:()=>api<Message[]>(`/management/messages?first_id=${selected!.student.id}&second_id=${selected!.advisor.id}`),enabled:Boolean(selected),refetchInterval:5000})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>
  return <div className="content-page"><Head title="نظارت بر گفت‌وگوها" text="مشاهده خواندنی مکالمات دانش‌آموز و مشاور در حوزه مجاز"/><div className="messages-layout"><aside>{data.map(item=><button key={`${item.student.id}-${item.advisor.id}`} className={selected?.student.id===item.student.id?'active':''} onClick={()=>setSelected(item)}><MessageSquare/><div><b>{item.student.full_name}</b><small>مشاور: {item.advisor.full_name}</small><small>{item.last_message||'بدون پیام'}</small></div></button>)}</aside><main>{selected?<div className="chat-shell monitor-chat"><header><ShieldCheck/><div><b>{selected.student.full_name} و {selected.advisor.full_name}</b><small>حالت نظارت خواندنی</small></div></header><div className="message-list">{messages.map(message=><article key={message.id} className={message.sender_id===selected.student.id?'mine':''}><p>{message.body}</p><small>{message.sender_id===selected.student.id?selected.student.full_name:selected.advisor.full_name} · {new Date(message.created_at).toLocaleString('fa-IR')}</small></article>)}</div></div>:<State text="یک گفت‌وگو را انتخاب کنید."/>}</main></div></div>
}

export function ManagerAdvisorsPage(){
  const qc=useQueryClient();const [selected,setSelected]=useState<AdminAdvisor>();const [note,setNote]=useState('');const {data=[],isLoading,error}=useQuery({queryKey:['management-advisors'],queryFn:()=>api<AdminAdvisor[]>('/management/advisors')});const review=useMutation({mutationFn:(status:string)=>api(`/management/advisors/${selected!.id}/review`,{method:'PATCH',body:JSON.stringify({status,note})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['management-advisors']});setSelected(undefined)}})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>
  return <div className="content-page"><Head title="تأیید مشاوران مقطع" text="بررسی مدارک و ارسال پرونده تأییدشده به مدیر سایت"/><div className="advisor-admin-grid"><aside>{data.map(item=><button key={item.id} onClick={()=>setSelected(item)}><span className="avatar">{item.full_name[0]}</span><div><b>{item.full_name}</b><small>{item.profile.education_field||'رشته ثبت نشده'}</small></div><strong>{item.profile.lead_approval_status==='approved'?'تأیید مسئول':'در انتظار بررسی'}</strong></button>)}</aside><main>{selected?<section className="advisor-detail"><h2>{selected.full_name}</h2><p>{selected.profile.bio}</p><div className="advisor-documents">{selected.profile.documents?.map(doc=><a key={doc.name} download={doc.name} href={`data:${doc.content_type};base64,${doc.content_base64}`}><Download/>{doc.kind}</a>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="برای رد مدارک، علت دقیق الزامی است"/><div className="review-actions"><button onClick={()=>review.mutate('approved')}><CheckCircle2/> تأیید و ارسال به مدیر</button><button disabled={!note.trim()} className="danger" onClick={()=>review.mutate('rejected')}><XCircle/> رد مدارک</button></div></section>:<State text="یک مشاور را انتخاب کنید."/>}</main></div>{review.error&&<ErrorBox error={review.error}/>}</div>
}

export function AdvisorRequestsPage(){
  const qc=useQueryClient();const [selected,setSelected]=useState<{student:User;profile:Profile}>();const {data=[],isLoading,error}=useQuery({queryKey:['advisor-assignment-requests'],queryFn:()=>api<{id:string;student:User;profile:Profile;created_at:string}[]>('/advisors/assignment-requests')});const decide=useMutation({mutationFn:({id,decision}:{id:string;decision:string})=>api(`/advisors/assignment-requests/${id}`,{method:'PATCH',body:JSON.stringify({decision,note:''})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['advisor-assignment-requests']});qc.invalidateQueries({queryKey:['advisor-dashboard']})}})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>
  return <div className="content-page"><Head title="درخواست‌های انتخاب مشاور" text="پیش از پذیرش، اطلاعات کامل فردی و تحصیلی دانش‌آموز را بررسی کنید."/><div className="admin-card-list">{data.map(item=><article className="panel assignment-request" key={item.id}><span className="avatar">{item.student.full_name[0]}</span><div><b>{item.student.full_name}</b><small>{item.profile.grade} · {item.profile.major||'بدون رشته'} · {item.profile.school}</small></div><button className="btn btn-soft" onClick={()=>setSelected(item)}>مشاهده اطلاعات کامل</button><div className="review-actions"><button disabled={decide.isPending} onClick={()=>decide.mutate({id:item.id,decision:'approved'})}><CheckCircle2/> پذیرش</button><button disabled={decide.isPending} className="danger" onClick={()=>decide.mutate({id:item.id,decision:'rejected'})}><XCircle/> رد</button></div></article>)}</div>{selected&&<section className="panel student-review-detail"><button className="detail-close" onClick={()=>setSelected(undefined)}><XCircle/></button><StudentProfileDetails student={selected.student} profile={selected.profile}/></section>}{!data.length&&<State text="درخواست جدیدی ندارید."/>}{decide.error&&<ErrorBox error={decide.error}/>}</div>
}

export function AdminStaffPage(){
  const qc=useQueryClient();const {data=[],isLoading,error}=useQuery({queryKey:['admin-staff'],queryFn:()=>api<(User&{created_at:string})[]>('/admin/staff')});const create=useMutation({mutationFn:(body:Record<string,unknown>)=>api('/admin/staff',{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:['admin-staff']})});const status=useMutation({mutationFn:({id,value}:{id:string;value:string})=>api(`/admin/users/${id}/status`,{method:'PATCH',body:JSON.stringify({status:value})}),onSuccess:()=>qc.invalidateQueries({queryKey:['admin-staff']})})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>
  return <div className="content-page"><Head title="منشی و مسئولان مقاطع" text="تعریف شماره موبایل کارکنان برای ورود با پیامک یکبار مصرف"/><form className="panel staff-create-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);create.mutate(Object.fromEntries(form));e.currentTarget.reset()}}><UserPlus/><input name="full_name" required placeholder="نام و نام خانوادگی"/><input name="phone" required pattern="09[0-9]{9}" placeholder="شماره موبایل"/><select name="role"><option value="secretary">منشی</option><option value="upper_secondary_manager">مسئول متوسطه دوم</option><option value="lower_secondary_manager">مسئول متوسطه اول</option></select><button className="btn btn-primary">افزودن کارمند</button></form>{create.error&&<ErrorBox error={create.error}/>}<div className="admin-table"><div className="admin-table-head"><span>نام</span><span>نقش</span><span>شماره</span><span>وضعیت</span><span>اقدام</span></div>{data.map(item=><div className="admin-table-row" key={item.id}><b>{item.full_name}</b><span>{roleNames[item.role]}</span><span>{item.phone}</span><span>{item.status==='active'?'فعال':'غیرفعال'}</span><button className="btn btn-soft" onClick={()=>status.mutate({id:item.id,value:item.status==='active'?'suspended':'active'})}>{item.status==='active'?'غیرفعال‌کردن':'فعال‌کردن'}</button></div>)}</div></div>
}
