import { useMutation } from '@tanstack/react-query'
import { FormEvent, ReactNode, useState } from 'react'
import { FileUp } from 'lucide-react'
import { api } from '../api'
import type { AdvisorDocument, SchoolSchedule } from '../types'

const days = ['شنبه', 'یکشنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه']
const emptySchedule = (): SchoolSchedule => Object.fromEntries(days.map(day => [day, ['', '', '', '']]))

export function StudentProfileForm({ refresh }: { refresh: () => void }) {
  const [grade, setGrade] = useState('دهم'); const [schedule, setSchedule] = useState<SchoolSchedule>(emptySchedule()); const [extras, setExtras] = useState<Record<string, string>>({})
  const save = useMutation({ mutationFn: (body: Record<string, unknown>) => api('/onboarding/student/profile', { method: 'POST', body: JSON.stringify(body) }), onSuccess: refresh })
  const lower=['هفتم','هشتم','نهم'].includes(grade)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const number = (name: string) => { const value=form.get(name); return value===null||value===''?null:Number(value) }; save.mutate({ full_name: form.get('full_name'), national_code: form.get('national_code'), birth_date: form.get('birth_date'), parent_name: form.get('parent_name'), parent_phone: form.get('parent_phone'), address: form.get('address'), grade, major: lower?'عمومی':form.get('major'), school: form.get('school'), goal: form.get('goal')||'', average_grade7: number('average_grade7'), average_grade8: number('average_grade8'), average_grade9: number('average_grade9'), average_grade10: number('average_grade10'), average_grade11: number('average_grade11'), average_grade12: number('average_grade12'), school_schedule: grade === 'پشت کنکوری' ? {} : schedule, extra_classes: extras }) }
  return <form className="registration-form onboarding-card" onSubmit={submit}><Title title="پرونده دانش‌آموز" text="اطلاعات این مرحله برای تعیین مقطع، نمایش مشاوران مرتبط و برنامه‌ریزی دقیق استفاده می‌شود." /><div className="form-grid"><Field label="نام و نام خانوادگی"><input name="full_name" required minLength={3} /></Field><Field label="کد ملی"><input name="national_code" required pattern="[0-9]{10}" /></Field><Field label="تاریخ تولد"><input name="birth_date" required placeholder="۱۳۸۸/۰۵/۱۲" /></Field><Field label="نام ولی"><input name="parent_name" required /></Field><Field label="موبایل ولی"><input name="parent_phone" required pattern="09[0-9]{9}" /></Field><Field label="پایه"><select value={grade} onChange={event=>setGrade(event.target.value)}><option>هفتم</option><option>هشتم</option><option>نهم</option><option>دهم</option><option>یازدهم</option><option>دوازدهم</option><option>پشت کنکوری</option></select></Field>{!lower&&<Field label="رشته تحصیلی"><input name="major" required placeholder="مثلاً تجربی" /></Field>}<Field label="مدرسه"><input name="school" required /></Field><Field label={lower?'هدف تحصیلی (اختیاری)':'هدف تحصیلی'}><input name="goal" required={!lower} /></Field><Field label="نشانی" wide><textarea name="address" required minLength={10} /></Field></div><AverageFields grade={grade} />{grade !== 'پشت کنکوری' && <ScheduleEditor schedule={schedule} setSchedule={setSchedule} extras={extras} setExtras={setExtras} />}{save.error && <ErrorText error={save.error} />}<button className="btn btn-primary btn-lg" disabled={save.isPending}>{save.isPending ? 'در حال ذخیره...' : 'ذخیره و مرحله بعد'}</button></form>
}

export function AdvisorProfileForm({ refresh }: { refresh: () => void }) {
  const [documents, setDocuments] = useState<AdvisorDocument[]>([]); const [fileError, setFileError] = useState('')
  const save = useMutation({ mutationFn: (body: Record<string, unknown>) => api('/onboarding/advisor/profile', { method: 'POST', body: JSON.stringify(body) }), onSuccess: refresh })
  async function files(selected: FileList | null) { setFileError(''); try { const result: AdvisorDocument[] = []; for (const [index, file] of Array.from(selected || []).entries()) { if (file.size > 4 * 1024 * 1024) throw new Error('حجم هر فایل باید کمتر از ۴ مگابایت باشد.'); const content_base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = reject; reader.readAsDataURL(file) }); result.push({ kind: index === 0 ? 'مدرک هویتی' : 'مدرک تحصیلی یا سابقه کار', name: file.name, content_type: file.type, content_base64 }) } setDocuments(result) } catch (error) { setDocuments([]); setFileError(error instanceof Error ? error.message : 'فایل معتبر نیست') } }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); save.mutate({ full_name: form.get('full_name'), national_code: form.get('national_code'), birth_date: form.get('birth_date'), address: form.get('address'), education_level: form.get('education_level'), education_degree: form.get('education_degree'), education_field: form.get('education_field'), experience_years: Number(form.get('experience_years')), bio: form.get('bio'), support_capacity: Number(form.get('support_capacity')), academic_year: form.get('academic_year'), documents }) }
  return <form className="registration-form onboarding-card" onSubmit={submit}><Title title="اطلاعات و مدارک مشاور" text="مدارک ابتدا توسط مسئول مقطع انتخابی و سپس مدیر سایت بررسی می‌شود. فعال‌سازی فقط بعد از هر دو تأیید انجام خواهد شد و پرداختی ندارد." /><div className="form-grid"><Field label="نام و نام خانوادگی"><input name="full_name" required minLength={3} /></Field><Field label="کد ملی"><input name="national_code" required pattern="[0-9]{10}" /></Field><Field label="تاریخ تولد"><input name="birth_date" required /></Field><Field label="مقطع فعالیت"><select name="education_level" required><option value="upper_secondary">متوسطه دوم</option><option value="lower_secondary">متوسطه اول</option></select></Field><Field label="مدرک تحصیلی"><input name="education_degree" required /></Field><Field label="رشته تحصیلی"><input name="education_field" required /></Field><Field label="سابقه کار (سال)"><input name="experience_years" type="number" min="0" max="60" required /></Field><Field label="ظرفیت سالانه"><input name="support_capacity" type="number" min="1" max="500" defaultValue="20" required /></Field><Field label="سال تحصیلی"><input name="academic_year" defaultValue="۱۴۰۵-۱۴۰۶" required /></Field><Field label="نشانی" wide><textarea name="address" required minLength={10} /></Field><Field label="معرفی و سابقه" wide><textarea name="bio" required minLength={20} /></Field><Field label="مدارک هویتی، تحصیلی و سابقه" wide><label className="file-drop"><FileUp /><b>{documents.length ? `${documents.length} فایل انتخاب شد` : 'حداقل دو فایل انتخاب کنید'}</b><small>PDF، JPG، PNG یا WEBP؛ حداکثر ۴ مگابایت</small><input type="file" multiple required accept=".pdf,image/jpeg,image/png,image/webp" onChange={event => files(event.target.files)} /></label></Field></div>{fileError && <div className="form-error">{fileError}</div>}{save.error && <ErrorText error={save.error} />}<button className="btn btn-primary btn-lg" disabled={save.isPending || documents.length < 2}>ارسال برای تأیید مسئول مقطع</button></form>
}

function ScheduleEditor({ schedule, setSchedule, extras, setExtras }: { schedule: SchoolSchedule; setSchedule: (value: SchoolSchedule) => void; extras: Record<string, string>; setExtras: (value: Record<string, string>) => void }) { return <div className="registration-section"><h3>برنامه مدرسه</h3><p>شنبه تا چهارشنبه، چهار زنگ و توضیحات فوق‌العاده را وارد کنید.</p><div className="school-schedule-editor">{days.map(day => <section key={day}><b>{day}</b>{schedule[day].map((value, index) => <input key={index} value={value} required placeholder={`زنگ ${index + 1}`} onChange={event => setSchedule({ ...schedule, [day]: schedule[day].map((item, itemIndex) => itemIndex === index ? event.target.value : item) })} />)}<textarea value={extras[day] || ''} placeholder="فوق‌العاده یا توضیحات" onChange={event => setExtras({ ...extras, [day]: event.target.value })} /></section>)}</div></div> }
function AverageFields({grade}:{grade:string}){const map:Record<string,[string,string,boolean][]>= {هفتم:[],هشتم:[['average_grade7','معدل هفتم',true]],نهم:[['average_grade7','معدل هفتم',false],['average_grade8','معدل هشتم',true]],دهم:[['average_grade7','معدل هفتم',false],['average_grade8','معدل هشتم',false],['average_grade9','معدل نهم',true]],یازدهم:[['average_grade10','معدل دهم',true]],دوازدهم:[['average_grade10','معدل دهم',false],['average_grade11','معدل یازدهم',true]],'پشت کنکوری':[['average_grade10','معدل دهم',false],['average_grade11','معدل یازدهم',false],['average_grade12','معدل دوازدهم',true]]};const fields=map[grade]||[];return <div className="registration-section"><h3>سوابق تحصیلی</h3>{fields.length?<div className="form-grid">{fields.map(([name,label,required])=><Field key={name} label={`${label}${required?' (الزامی)':' (اختیاری)'}`}><input name={name} type="number" min="0" max="20" step="0.01" required={required}/></Field>)}</div>:<p>برای پایه هفتم نیازی به ثبت معدل سال قبل نیست.</p>}</div>}
function Field({ label, wide, children }: { label: string; wide?: boolean; children: ReactNode }) { return <label className={wide ? 'wide' : ''}><span>{label}</span>{children}</label> }
function Title({ title, text }: { title: string; text: string }) { return <div className="form-title"><div><h2>{title}</h2><p>{text}</p></div></div> }
function ErrorText({ error }: { error: unknown }) { return <div className="form-error">{error instanceof Error ? error.message : 'خطایی رخ داد'}</div> }
