import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, BookOpen, CheckCircle2, Clock3, MessageSquare, Plus, Save, Search, Send, Trash2, TrendingUp, UserRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'
import type { ExamListItem, Message, PlanActivity, Profile, ReportData, User, WeeklyPlan } from '../types'

const days=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه']
const fmt=(date?:string)=>date?new Intl.DateTimeFormat('fa-IR',{hour:'2-digit',minute:'2-digit',month:'short',day:'numeric'}).format(new Date(date)):''
function PageHead({title,subtitle,back}:{title:string;subtitle:string;back?:()=>void}){return <div className="section-head">{back&&<button className="icon-btn" onClick={back}><ArrowRight/></button>}<div><h1>{title}</h1><p>{subtitle}</p></div></div>}
function State({text='در حال دریافت اطلاعات...'}:{text?:string}){return <div className="page-state">{text}</div>}
function ErrorBox({error}:{error:unknown}){return <div className="error-box">{error instanceof Error?error.message:'خطایی رخ داد'}</div>}

export function StudentPlanPage(){
  const qc=useQueryClient();const {data,isLoading,error}=useQuery({queryKey:['plans'],queryFn:()=>api<WeeklyPlan[]>('/plans')})
  const update=useMutation({mutationFn:({item,form}:{item:PlanActivity;form:FormData})=>api(`/activities/${item.id}`,{method:'PATCH',body:JSON.stringify({status:form.get('status'),actual_minutes:Number(form.get('actual_minutes')),test_count:Number(form.get('test_count')),note:form.get('note'),idempotency_key:crypto.randomUUID()})}),onSuccess:()=>qc.invalidateQueries({queryKey:['plans']})})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>;const plan=data?.[0]
  return <div className="content-page"><PageHead title="برنامه من" subtitle="برنامه منتشرشده مشاور و ثبت عملکرد واقعی"/>{!plan?<State text="هنوز برنامه‌ای برای شما منتشر نشده است."/>:<><div className="plan-banner"><div><b>{plan.title}</b><span>{plan.week_label} · نسخه {plan.version}</span></div><CheckCircle2/> منتشرشده</div><div className="week-board">{days.map(day=><section key={day}><h3>{day}</h3>{plan.activities.filter(a=>a.day===day).map(item=><form key={item.id} className="schedule-card" onSubmit={e=>{e.preventDefault();update.mutate({item,form:new FormData(e.currentTarget)})}}><div className="schedule-time"><Clock3/>{item.start_time} تا {item.end_time}</div><b>{item.title}</b><small>{item.subject} · {item.planned_minutes} دقیقه</small><div className="inline-fields"><select name="status" defaultValue={item.status}><option value="pending">انجام نشده</option><option value="in_progress">در حال انجام</option><option value="completed">انجام شد</option></select><input name="actual_minutes" type="number" min="0" defaultValue={item.actual_minutes} aria-label="زمان واقعی"/><input name="test_count" type="number" min="0" defaultValue={item.test_count} aria-label="تعداد تست"/></div><input name="note" defaultValue={item.note} placeholder="یادداشت عملکرد..."/><button className="small-primary" disabled={update.isPending}><Save/> ثبت عملکرد</button></form>)}</section>)}</div></>}</div>
}

export function ProgressPage({studentId}:{studentId?:string}){
  const path=studentId?`/advisors/students/${studentId}/report`:'/students/report';const {data,isLoading,error}=useQuery({queryKey:['report',studentId],queryFn:()=>api<ReportData&{student?:User;profile?:Record<string,string>}>(path)})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>;if(!data)return null
  return <div className="content-page"><PageHead title={data.student?`گزارش ${data.student.full_name}`:'گزارش پیشرفت'} subtitle="مقایسه برنامه‌ریزی و عملکرد واقعی"/><div className="summary-cards"><article><TrendingUp/><span>اجرای برنامه</span><b>{data.summary.progress}٪</b></article><article><Clock3/><span>مطالعه واقعی</span><b>{data.summary.actual_minutes} دقیقه</b></article><article><BookOpen/><span>تعداد تست</span><b>{data.summary.test_count}</b></article><article><CheckCircle2/><span>فعالیت کامل</span><b>{data.summary.completed} از {data.summary.total}</b></article></div><div className="two-col"><section className="panel"><h2>عملکرد درسی</h2><div className="subject-bars">{data.subjects.map(s=><div key={s.subject}><p><b>{s.subject}</b><span>{s.actual_minutes} از {s.planned_minutes} دقیقه · {s.tests} تست</span></p><i><b style={{width:`${Math.min(100,s.planned_minutes?s.actual_minutes/s.planned_minutes*100:0)}%`}}/></i></div>)}</div></section><section className="panel"><h2>نتایج آزمون‌ها</h2>{data.results.length?data.results.map(r=><div className="result-row" key={r.id}><div><b>{r.title}</b><small>{r.correct} درست · {r.wrong} غلط</small></div><strong>{r.score}٪</strong></div>):<State text="نتیجه آزمونی ثبت نشده است."/>}</section><section className="panel span-2"><h2>فعالیت‌های اخیر</h2><div className="report-table">{data.activities.slice(-12).reverse().map(a=><div key={a.id}><span>{a.day}، {a.start_time}</span><b>{a.title}</b><span>{a.actual_minutes}/{a.planned_minutes} دقیقه</span><em className={a.status}>{a.status==='completed'?'انجام شد':a.status==='in_progress'?'در حال انجام':'انجام نشده'}</em></div>)}</div></section></div></div>
}

export function SettingsPage(){
  const qc=useQueryClient();const {data,isLoading,error}=useQuery({queryKey:['profile'],queryFn:()=>api<Profile>('/profile')});const save=useMutation({mutationFn:(form:FormData)=>api('/profile',{method:'PATCH',body:JSON.stringify(Object.fromEntries(form))}),onSuccess:()=>{qc.invalidateQueries({queryKey:['profile']});qc.invalidateQueries({queryKey:['me']})}})
  if(isLoading)return <State/>;if(error||!data)return <ErrorBox error={error}/>
  return <div className="content-page narrow"><PageHead title="تنظیمات" subtitle="اطلاعات حساب و پروفایل تحصیلی"/><form className="settings-form panel" onSubmit={e=>{e.preventDefault();save.mutate(new FormData(e.currentTarget))}}><label>نام و نام خانوادگی<input name="full_name" defaultValue={data.full_name} required/></label><label>شماره ورود<input value={data.phone} disabled/></label>{data.role==='student'&&<><label>پایه<input name="grade" defaultValue={data.grade}/></label><label>رشته<input name="major" defaultValue={data.major}/></label><label>مدرسه<input name="school" defaultValue={data.school}/></label><label className="full">هدف تحصیلی<textarea name="goal" defaultValue={data.goal}/></label></>}<button className="btn btn-primary" disabled={save.isPending}><Save/> ذخیره تغییرات</button>{save.isSuccess&&<span className="success-note">تغییرات ذخیره شد.</span>}</form></div>
}

export function ChatPanel({counterpart,currentUser}:{counterpart:User;currentUser:User}){
  const qc=useQueryClient();const {data=[],isLoading,error}=useQuery({queryKey:['messages',counterpart.id],queryFn:()=>api<Message[]>(`/messages?counterpart_id=${counterpart.id}`),refetchInterval:5000})
  useEffect(()=>{if(data.length)api(`/messages/${counterpart.id}/read`,{method:'POST'}).then(()=>qc.invalidateQueries({queryKey:['messages',counterpart.id]})).catch(()=>{})},[data.length,counterpart.id,qc])
  const send=useMutation({mutationFn:(body:string)=>api('/messages',{method:'POST',body:JSON.stringify({recipient_id:counterpart.id,body})}),onSuccess:()=>qc.invalidateQueries({queryKey:['messages',counterpart.id]})})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>
  return <div className="chat-shell"><header><span className="avatar">{counterpart.full_name[0]}</span><div><b>{counterpart.full_name}</b><small>{counterpart.role==='advisor'?'مشاور شما':'دانش‌آموز'}</small></div><i>به‌روزرسانی خودکار</i></header><div className="message-list">{!data.length&&<State text="هنوز پیامی ردوبدل نشده است."/>}{data.map(m=><article key={m.id} className={m.sender_id===currentUser.id?'mine':''}><p>{m.body}</p><small>{fmt(m.created_at)} {m.sender_id===currentUser.id&&(m.read_at?'· خوانده شد':'· ارسال شد')}</small></article>)}</div><form onSubmit={e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('message') as HTMLInputElement;if(input.value.trim()){send.mutate(input.value.trim());input.value=''}}}><input name="message" maxLength={3000} autoComplete="off" placeholder="پیام خود را بنویسید..."/><button disabled={send.isPending}><Send/></button></form></div>
}

export function StudentChatPage({user}:{user:User}){const {data,isLoading,error}=useQuery({queryKey:['my-advisor'],queryFn:()=>api<User|null>('/students/advisor')});if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>;return <div className="content-page narrow"><PageHead title="گفت‌وگو با مشاور" subtitle="ارتباط مستقیم با مشاور اختصاصی"/>{data?<ChatPanel counterpart={data} currentUser={user}/>:<State text="هنوز مشاوری به شما تخصیص داده نشده است."/>}</div>}

type ExamRun={session_id:string;duration_minutes:number;questions:{id:string;text:string;options:string[]}[]}
export function ExamsPage(){
  const qc=useQueryClient();const [run,setRun]=useState<ExamRun>();const [answers,setAnswers]=useState<Record<string,number>>({});const [left,setLeft]=useState(0);const {data,isLoading,error}=useQuery({queryKey:['exams'],queryFn:()=>api<ExamListItem[]>('/exams')})
  useEffect(()=>{if(!run)return;setLeft(run.duration_minutes*60);const timer=setInterval(()=>setLeft(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[run])
  const start=useMutation({mutationFn:(id:string)=>api<ExamRun>(`/exam-sessions/${id}/start`,{method:'POST'}),onSuccess:r=>setRun(r)})
  const submit=useMutation({mutationFn:async()=>{if(!run)return;for(const [question_id,selected_index] of Object.entries(answers))await api(`/exam-sessions/${run.session_id}/answers`,{method:'PUT',body:JSON.stringify({question_id,selected_index,elapsed_seconds:0,client_version:1,idempotency_key:crypto.randomUUID()})});return api(`/exam-sessions/${run.session_id}/submit`,{method:'POST'})},onSuccess:()=>{setRun(undefined);setAnswers({});qc.invalidateQueries({queryKey:['exams']})}})
  if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>
  if(run)return <div className="content-page exam-run"><div className="exam-top"><PageHead title="در حال برگزاری آزمون" subtitle={`${run.questions.length} سؤال`}/><b><Clock3/>{Math.floor(left/60).toString().padStart(2,'0')}:{(left%60).toString().padStart(2,'0')}</b></div>{run.questions.map((q,i)=><section className="question-card" key={q.id}><h3>{i+1}. {q.text}</h3>{q.options.map((o,j)=><label key={j} className={answers[q.id]===j?'chosen':''}><input type="radio" name={q.id} onChange={()=>setAnswers(a=>({...a,[q.id]:j}))}/>{o}</label>)}</section>)}<button className="btn btn-primary" disabled={submit.isPending} onClick={()=>submit.mutate()}>ثبت و پایان آزمون</button></div>
  return <div className="content-page"><PageHead title="آزمون‌ها" subtitle="آزمون‌های فعال و نتایج ثبت‌شده"/><div className="exam-grid">{data?.map(exam=><article className="panel" key={exam.id}><BookOpen/><div><h2>{exam.title}</h2><p>{exam.question_count} سؤال · {exam.duration_minutes} دقیقه</p></div>{exam.session?.status==='submitted'?<strong className="exam-score">{exam.session.score}٪</strong>:<button className="small-primary" onClick={()=>start.mutate(exam.id)}>شروع آزمون</button>}</article>)}</div></div>
}

type AdvisorStudent=User&{risk:string;progress:number;last_activity?:string;last_message?:string;last_message_at?:string}
export function AdvisorStudentsPage(){const nav=useNavigate();const [search,setSearch]=useState('');const {data,isLoading,error}=useQuery({queryKey:['advisor-dashboard'],queryFn:()=>api<{students:AdvisorStudent[]}>('/advisors/dashboard')});const rows=useMemo(()=>data?.students.filter(s=>s.full_name.includes(search))||[],[data,search]);if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>;return <div className="content-page"><PageHead title="دانش‌آموزان" subtitle="پرونده، عملکرد، برنامه و پیام‌های دانش‌آموزان شما"/><div className="list-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی نام دانش‌آموز..."/></div><div className="student-cards">{rows.map(s=><button key={s.id} onClick={()=>nav(`/app/advisor/students/${s.id}/report`)}><span className="avatar">{s.full_name[0]}</span><div><b>{s.full_name}</b><small>{s.last_activity||'بدون فعالیت اخیر'}</small><p>{s.last_message||'بدون پیام اخیر'}</p></div><em className={s.risk==='بالا'?'high':''}>{s.risk}</em><strong>{s.progress}٪</strong></button>)}</div></div>}

type DraftActivity={day:string;subject:string;title:string;start_time:string;end_time:string}
function PlanBuilder({studentId}:{studentId:string}){const qc=useQueryClient();const [title,setTitle]=useState('برنامه هفتگی');const [week,setWeek]=useState('هفته جاری');const [items,setItems]=useState<DraftActivity[]>([{day:'شنبه',subject:'',title:'',start_time:'08:00',end_time:'09:00'}]);const {data}=useQuery({queryKey:['plans','advisor'],queryFn:()=>api<WeeklyPlan[]>('/plans')});const create=useMutation({mutationFn:async()=>{const plan=await api<{id:string}>('/plans',{method:'POST',body:JSON.stringify({student_id:studentId,title,week_label:week,activities:items})});await api(`/plans/${plan.id}/publish`,{method:'POST'});return plan},onSuccess:()=>qc.invalidateQueries({queryKey:['plans','advisor']})});const update=(i:number,key:keyof DraftActivity,value:string)=>setItems(all=>all.map((x,n)=>n===i?{...x,[key]:value}:x));return <div className="planner"><div className="planner-meta"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان برنامه"/><input value={week} onChange={e=>setWeek(e.target.value)} placeholder="بازه هفته"/></div>{items.map((item,i)=><div className="planner-row" key={i}><select value={item.day} onChange={e=>update(i,'day',e.target.value)}>{days.map(d=><option key={d}>{d}</option>)}</select><input type="time" step="900" value={item.start_time} onChange={e=>update(i,'start_time',e.target.value)}/><input type="time" step="900" value={item.end_time} onChange={e=>update(i,'end_time',e.target.value)}/><input value={item.subject} onChange={e=>update(i,'subject',e.target.value)} placeholder="درس"/><input value={item.title} onChange={e=>update(i,'title',e.target.value)} placeholder="عنوان فعالیت"/><button onClick={()=>setItems(a=>a.filter((_,n)=>n!==i))}><Trash2/></button></div>)}<div className="planner-actions"><button className="small-secondary" onClick={()=>setItems(a=>[...a,{day:'شنبه',subject:'',title:'',start_time:'08:00',end_time:'09:00'}])}><Plus/> افزودن بازه</button><button className="btn btn-primary" disabled={create.isPending||items.some(x=>!x.subject||!x.title)} onClick={()=>create.mutate()}><Save/> ذخیره و انتشار</button></div>{create.error&&<ErrorBox error={create.error}/>}<h2>نسخه‌های قبلی</h2>{data?.filter(p=>p.student_id===studentId).map(p=><div className="version-row" key={p.id}><b>{p.title}</b><span>{p.week_label} · نسخه {p.version}</span><em>{p.status==='published'?'منتشرشده':'پیش‌نویس'}</em></div>)}</div>}

export function StudentFilePage({user,studentId,tab}:{user:User;studentId:string;tab:string}){const nav=useNavigate();const {data,isLoading,error}=useQuery({queryKey:['student-file',studentId],queryFn:()=>api<ReportData&{student:User}>(`/advisors/students/${studentId}/report`)});if(isLoading)return <State/>;if(error||!data)return <ErrorBox error={error}/>;return <div className="content-page"><PageHead back={()=>nav('/app/advisor/students')} title={data.student.full_name} subtitle="پرونده اختصاصی دانش‌آموز"/><div className="file-tabs"><button className={tab==='report'?'active':''} onClick={()=>nav(`/app/advisor/students/${studentId}/report`)}>گزارش عملکرد</button><button className={tab==='plan'?'active':''} onClick={()=>nav(`/app/advisor/students/${studentId}/plan`)}>برنامه هفتگی</button><button className={tab==='chat'?'active':''} onClick={()=>nav(`/app/advisor/students/${studentId}/chat`)}>گفت‌وگو</button></div>{tab==='report'?<ProgressPage studentId={studentId}/>:tab==='plan'?<PlanBuilder studentId={studentId}/>:<ChatPanel counterpart={data.student} currentUser={user}/>}</div>}

export function AdvisorMessagesPage({user}:{user:User}){const [selected,setSelected]=useState<User>();const {data,isLoading,error}=useQuery({queryKey:['advisor-dashboard'],queryFn:()=>api<{students:AdvisorStudent[]}>('/advisors/dashboard')});if(isLoading)return <State/>;if(error)return <ErrorBox error={error}/>;return <div className="content-page"><PageHead title="پیام‌ها" subtitle="گفت‌وگوهای شما با دانش‌آموزان"/><div className="messages-layout"><aside>{data?.students.map(s=><button className={selected?.id===s.id?'active':''} onClick={()=>setSelected(s)} key={s.id}><span className="avatar">{s.full_name[0]}</span><div><b>{s.full_name}</b><small>{s.last_message||'شروع گفت‌وگو'}</small></div></button>)}</aside><main>{selected?<ChatPanel counterpart={selected} currentUser={user}/>:<State text="یک دانش‌آموز را برای گفت‌وگو انتخاب کنید."/>}</main></div></div>}
