import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarClock, CheckCircle2, CreditCard, Receipt } from 'lucide-react'
import { api } from '../api'
import { faNumber, formatJalali, formatJalaliDateTime } from '../utils/jalali'

type Overview={current?:{id:string;plan_name:string;starts_at:string;expires_at:string;remaining_days:number;status:string}|null;approval:{admin:string;advisor:string};subscriptions:{id:string;plan_name:string;starts_at:string;expires_at:string;status:string}[];payments:{id:string;plan_name:string;amount:number;status:string;created_at:string}[]}
type Offer={order_id:string;amount:number;expires_at:string;signature:string}|null
const labels:Record<string,string>={active:'فعال',pending_activation:'در انتظار تأیید',paid:'پرداخت‌شده',pending:'در انتظار پرداخت',failed:'ناموفق',approved:'تأییدشده',rejected:'ردشده'}
export default function StudentSubscriptionPage(){
 const qc=useQueryClient()
 const overview=useQuery({queryKey:['student-subscription-overview'],queryFn:()=>api<Overview>('/students/subscription-overview')})
 const offer=useQuery({queryKey:['pending-subscription-offer'],queryFn:()=>api<Offer>('/subscriptions/pending-offer')})
 const pay=useMutation({mutationFn:(item:Exclude<Offer,null>)=>api('/payments/callback',{method:'POST',body:JSON.stringify({order_id:item.order_id,success:true,signature:item.signature})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['me']});qc.invalidateQueries({queryKey:['student-subscription-overview']});qc.invalidateQueries({queryKey:['pending-subscription-offer']})}})
 if(overview.isLoading)return <div className="page-state">در حال دریافت اطلاعات اشتراک...</div>
 if(overview.error||!overview.data)return <div className="error-box">دریافت وضعیت اشتراک ناموفق بود.</div>
 const data=overview.data
 return <div className="content-page"><div className="section-head"><div><h1>اشتراک و پرداخت‌های من</h1><p>وضعیت فعال‌سازی، روزهای باقی‌مانده و تاریخچه کامل پرداخت‌ها.</p></div></div><div className="subscription-overview-grid"><section className="panel current-subscription"><CalendarClock/><h2>وضعیت اشتراک</h2>{data.current?<><strong>{faNumber(data.current.remaining_days)} روز باقی مانده</strong><p>{data.current.plan_name}</p><small>شروع: {formatJalali(data.current.starts_at)} · پایان: {formatJalali(data.current.expires_at)}</small></>:<><strong>اشتراک فعال ندارید</strong><p>در صورت پرداخت اولیه، دوره پس از تأیید مدیر و مشاور شروع می‌شود.</p></>}</section><section className="panel approval-status"><CheckCircle2/><h2>وضعیت تأیید ثبت‌نام</h2><p>مدیر: <b>{labels[data.approval.admin]||data.approval.admin}</b></p><p>مشاور: <b>{labels[data.approval.advisor]||data.approval.advisor}</b></p></section></div>{offer.data&&<section className="panel subscription-offer"><CreditCard/><h2>درخواست تمدید مدیر</h2><p>مبلغ {faNumber(offer.data.amount.toLocaleString('en-US'))} تومان برای تمدید تا {formatJalali(offer.data.expires_at)}</p><button className="btn btn-primary" disabled={pay.isPending} onClick={()=>offer.data&&pay.mutate(offer.data)}>پرداخت و فعال‌سازی</button></section>}<section className="panel"><h2><Receipt/> تاریخچه پرداخت‌ها</h2><div className="admin-table"><div className="admin-table-head finance"><span>طرح</span><span>مبلغ</span><span>وضعیت</span><span>تاریخ</span></div>{data.payments.map(item=><div className="admin-table-row finance" key={item.id}><b>{item.plan_name}</b><span>{faNumber(item.amount.toLocaleString('en-US'))} تومان</span><span>{labels[item.status]||item.status}</span><span>{formatJalaliDateTime(item.created_at)}</span></div>)}{!data.payments.length&&<div className="empty-state">پرداختی ثبت نشده است.</div>}</div></section><section className="panel"><h2>دوره‌های اشتراک</h2><div className="admin-table"><div className="admin-table-head finance"><span>طرح</span><span>شروع</span><span>پایان</span><span>وضعیت</span></div>{data.subscriptions.map(item=><div className="admin-table-row finance" key={item.id}><b>{item.plan_name}</b><span>{formatJalali(item.starts_at)}</span><span>{formatJalali(item.expires_at)}</span><span>{labels[item.status]||item.status}</span></div>)}</div></section></div>
}
