import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Lock, MessageSquare, Search, Send, Unlock } from 'lucide-react'
import { api } from '../api'
import type { Message, User } from '../types'
import { formatJalaliDateTime } from '../utils/jalali'
type Contact=User&{last_message?:string;locked:boolean}
const roleName:Record<string,string>={student:'دانش‌آموز',advisor:'مشاور',secretary:'منشی',upper_secondary_manager:'مسئول متوسطه دوم',lower_secondary_manager:'مسئول متوسطه اول',finance:'مدیر مالی',operations_admin:'مدیر عملیات',super_admin:'مدیر سایت',support:'پشتیبان',content_editor:'کارشناس محتوا',reviewer:'بازبین علمی',exam_designer:'طراح آزمون'}
export default function UniversalChatPage({user}:{user:User}){
 const qc=useQueryClient(),[selected,setSelected]=useState<Contact>(),[search,setSearch]=useState('')
 const contacts=useQuery({queryKey:['chat-contacts'],queryFn:()=>api<Contact[]>('/chat/contacts'),refetchInterval:5000})
 const alerts=useQuery({queryKey:['notification-summary'],queryFn:()=>api<{unread_by_sender:Record<string,number>}>('/notifications/summary'),refetchInterval:5000})
 const messages=useQuery({queryKey:['universal-messages',selected?.id],queryFn:()=>api<Message[]>('/messages?counterpart_id='+selected!.id),enabled:Boolean(selected),refetchInterval:5000})
 useEffect(()=>{if(selected&&messages.data?.length)api('/messages/'+selected.id+'/read',{method:'POST'}).then(()=>{qc.invalidateQueries({queryKey:['notification-summary']});qc.invalidateQueries({queryKey:['notifications']})}).catch(()=>{})},[selected?.id,messages.data?.length,qc])
 const send=useMutation({mutationFn:(body:string)=>api('/messages',{method:'POST',body:JSON.stringify({recipient_id:selected!.id,body})}),onSuccess:()=>qc.invalidateQueries({queryKey:['universal-messages',selected?.id]})})
 const lock=useMutation({mutationFn:(locked:boolean)=>api<{locked:boolean}>('/admin/chat-locks/'+selected!.id,{method:'PATCH',body:JSON.stringify({locked})}),onSuccess:data=>{setSelected(current=>current?{...current,locked:data.locked}:current);qc.invalidateQueries({queryKey:['chat-contacts']})}})
 const rows=useMemo(()=>(contacts.data||[]).filter(item=>item.full_name.includes(search)||item.phone.includes(search)||String(roleName[item.role]||item.role).includes(search)),[contacts.data,search])
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),body=String(form.get('body')||'').trim();if(body){send.mutate(body);event.currentTarget.reset()}}
 const blocked=Boolean(selected?.locked&&user.role!=='super_admin')
 return <div className="content-page"><div className="section-head"><div><h1>گفت‌وگوها</h1><p>{user.role==='super_admin'?'ارتباط مستقیم با همه نقش‌ها و مدیریت دسترسی هر گفتگو':'پیام‌های مشاور، مدیر و مخاطبان مجاز شما در یک صندوق مشترک'}</p></div></div><div className="messages-layout universal-chat"><aside><div className="chat-contact-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی نام، شماره یا نقش..."/></div>{rows.map(item=><button className={selected?.id===item.id?'active':''} key={item.id} onClick={()=>setSelected(item)}><span className="avatar">{item.full_name[0]}</span><div><b>{item.full_name}</b><small>{roleName[item.role]||item.role} · {item.phone}</small><small>{item.last_message||'شروع گفت‌وگو'}</small></div>{item.locked&&<Lock className="contact-lock"/>}{!!alerts.data?.unread_by_sender[item.id]&&<i className="conversation-alert-dot"/>}</button>)}</aside><main>{selected?<div className="chat-shell"><header><MessageSquare/><div><b>{selected.full_name}</b><small>{roleName[selected.role]||selected.role}</small></div>{user.role==='super_admin'&&<button className={'chat-lock-button '+(selected.locked?'locked':'')} onClick={()=>lock.mutate(!selected.locked)}>{selected.locked?<><Unlock/> بازکردن گفتگو</>:<><Lock/> قفل پاسخ کاربر</>}</button>}</header><div className="message-list">{messages.data?.map(item=><article className={item.sender_id===user.id?'mine':''} key={item.id}><p>{item.body}</p><small>{formatJalaliDateTime(item.created_at)}{item.sender_id===user.id&&(item.read_at?' · خوانده شد':' · ارسال شد')}</small></article>)}</div>{blocked?<div className="chat-blocked"><Lock/>این گفتگو توسط مدیر قفل شده است؛ امکان ارسال پاسخ ندارید.</div>:<form className="message-compose" onSubmit={submit}><input name="body" required maxLength={3000} placeholder="پیام خود را بنویسید..."/><button disabled={send.isPending}><Send/></button></form>}{send.error&&<div className="error-box">{send.error instanceof Error?send.error.message:'ارسال پیام ناموفق بود'}</div>}</div>:<div className="page-state">یک مخاطب را انتخاب کنید.</div>}</main></div></div>
}
