import { Activity as ActivityIcon, Bell, BookOpen, BrainCircuit, ChevronLeft, ClipboardCheck, CreditCard, FileQuestion, GraduationCap, Home, LogOut, Menu, MessageSquare, Search, Settings, ShieldCheck, Sparkles, TrendingUp, UserRound, Users, X } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { api, auth } from '../api'
import Brand from '../components/Brand'
import ChartCard from '../components/ChartCard'
import type { Activity, Insight, User } from '../types'
import { AdvisorMessagesPage, AdvisorStudentsPage, ExamsPage, ProgressPage, SettingsPage, StudentChatPage, StudentFilePage, StudentPlanPage } from './OperationalPages'

type StudentData={user:User;profile:{grade:string;major:string;goal:string};progress:number;study_minutes:number;activities:Activity[];exams:{id:string;title:string;duration_minutes:number}[];insights:Insight[]}
type AdvisorData={user:User;students:(User&{risk:string;progress:number})[];pending_insights:number;alerts:number;weekly_plans:number}
type AdminData={user:User;counts:Record<string,number>;service:{status:string;database:string;jobs:string}}

const roleLabels:Record<string,string>={student:'دانش‌آموز',advisor:'مشاور',content_editor:'کارشناس محتوا',reviewer:'بازبین علمی',exam_designer:'طراح آزمون',support:'پشتیبان',finance:'مدیر مالی',operations_admin:'مدیر عملیات',super_admin:'مدیر سیستم'}

export default function WorkspacePage({user}:{user:User}){
  const [mobile,setMobile]=useState(false);const nav=useNavigate();const location=useLocation();const qc=useQueryClient()
  const logout=async()=>{await auth.logout();qc.clear();nav('/')}
  const go=(path:string)=>{nav(path);setMobile(false)};const active=(path:string)=>location.pathname===path||location.pathname.startsWith(`${path}/`)
  const studentBase='/app/student',advisorBase='/app/advisor'
  let content:React.ReactNode
  if(user.role==='student'){
    const path=location.pathname
    content=path.includes('/plan')?<StudentPlanPage/>:path.includes('/exams')?<ExamsPage/>:path.includes('/progress')?<ProgressPage/>:path.includes('/chat')?<StudentChatPage user={user}/>:path.includes('/settings')?<SettingsPage/>:<StudentDashboard/>
  }else if(user.role==='advisor'){
    const match=location.pathname.match(/\/students\/([^/]+)\/(report|plan|chat)/)
    content=match?<StudentFilePage user={user} studentId={match[1]} tab={match[2]}/>:location.pathname.includes('/students')||location.pathname.includes('/planner')?<AdvisorStudentsPage/>:location.pathname.includes('/messages')?<AdvisorMessagesPage user={user}/>:location.pathname.includes('/settings')?<SettingsPage/>:<AdvisorDashboard/>
  }else content=<AdminDashboard user={user}/>
  return <div className="workspace"><aside className={`app-sidebar ${mobile?'open':''}`}><button className="sidebar-close" onClick={()=>setMobile(false)}><X/></button><Brand light/><nav><button className={active(`${user.role==='student'?studentBase:advisorBase}/overview`)?'selected':''} onClick={()=>go(`${user.role==='student'?studentBase:advisorBase}/overview`)}><Home/>نمای کلی</button>{user.role==='student'&&<><button className={active(`${studentBase}/plan`)?'selected':''} onClick={()=>go(`${studentBase}/plan`)}><ClipboardCheck/>برنامه من</button><button className={active(`${studentBase}/exams`)?'selected':''} onClick={()=>go(`${studentBase}/exams`)}><BookOpen/>آزمون‌ها</button><button className={active(`${studentBase}/progress`)?'selected':''} onClick={()=>go(`${studentBase}/progress`)}><TrendingUp/>گزارش پیشرفت</button><button className={active(`${studentBase}/chat`)?'selected':''} onClick={()=>go(`${studentBase}/chat`)}><MessageSquare/>گفت‌وگو با مشاور</button></>}{user.role==='advisor'&&<><button className={active(`${advisorBase}/students`)?'selected':''} onClick={()=>go(`${advisorBase}/students`)}><Users/>دانش‌آموزان</button><button className={active(`${advisorBase}/planner`)?'selected':''} onClick={()=>go(`${advisorBase}/planner`)}><ClipboardCheck/>برنامه‌ساز</button><button><BrainCircuit/>پیشنهادهای AI</button><button className={active(`${advisorBase}/messages`)?'selected':''} onClick={()=>go(`${advisorBase}/messages`)}><MessageSquare/>پیام‌ها</button></>}{!['student','advisor'].includes(user.role)&&<><button><Users/>کاربران</button><button><FileQuestion/>بانک سؤال</button><button><BookOpen/>آزمون‌ها</button><button><CreditCard/>اشتراک و مالی</button><button><ShieldCheck/>ممیزی</button></>}<button className={active(`${user.role==='student'?studentBase:advisorBase}/settings`)?'selected':''} onClick={()=>go(`${user.role==='student'?studentBase:advisorBase}/settings`)}><Settings/>تنظیمات</button></nav><button className="sidebar-logout" onClick={logout}><LogOut/>خروج</button></aside><main className="app-main"><header className="app-header"><button className="app-menu" onClick={()=>setMobile(true)}><Menu/></button><div className="app-search"><Search/><input placeholder="جست‌وجو در مسیر هوشمند..."/></div><div className="app-user"><button><Bell/><i/></button><span className="avatar">{user.full_name[0]}</span><p><b>{user.full_name}</b><small>{roleLabels[user.role]}</small></p></div></header>{content}</main></div>
}

function StudentDashboard(){const {data,isLoading}=useQuery({queryKey:['student-dashboard'],queryFn:()=>api<StudentData>('/students/dashboard')});const mutation=useMutation({mutationFn:(a:Activity)=>api(`/activities/${a.id}`,{method:'PATCH',body:JSON.stringify({status:'completed',actual_minutes:a.planned_minutes,test_count:20,note:'ثبت سریع از داشبورد',idempotency_key:crypto.randomUUID()})}),onSuccess:()=>location.reload()});if(isLoading||!data)return <Loading/>;return <div className="dashboard-page"><Welcome name={data.user.full_name} subtitle={`امروز یک قدم دیگر به هدف «${data.profile.goal}» نزدیک شو.`}/><div className="metric-grid"><Metric icon={TrendingUp} label="پیشرفت هفتگی" value={`${data.progress}٪`} tone="purple"/><Metric icon={ActivityIcon} label="زمان مطالعه" value={`${data.study_minutes} دقیقه`} tone="blue"/><Metric icon={ClipboardCheck} label="فعالیت امروز" value={`${data.activities.length} مورد`} tone="orange"/><Metric icon={BrainCircuit} label="بینش تازه" value={`${data.insights.length} مورد`} tone="green"/></div><div className="dashboard-grid"><section className="panel span-2"><PanelTitle title="برنامه این هفته" action="مشاهده برنامه"/><div className="activity-list">{data.activities.map(a=><article key={a.id}><span className={`status-dot ${a.status}`}/><div><b>{a.title}</b><small>{a.day} · {a.subject} · {a.planned_minutes} دقیقه</small></div><button disabled={a.status==='completed'||mutation.isPending} onClick={()=>mutation.mutate(a)}>{a.status==='completed'?'انجام شد':'ثبت انجام'}</button></article>)}</div></section><section className="panel"><PanelTitle title="پیشرفت کلی"/><div className="dashboard-donut" style={{'--progress':`${data.progress*3.6}deg`} as React.CSSProperties}><b>{data.progress}٪</b><span>اجرای برنامه</span></div><div className="mini-legend"><span><i className="purple"/>انجام‌شده</span><span><i/>باقی‌مانده</span></div></section><section className="panel span-2"><PanelTitle title="روند عملکرد" action="گزارش کامل"/><ChartCard/></section><section className="panel"><PanelTitle title="پیشنهادهای مسیر هوشمند"/><div className="insight-list">{data.insights.map(i=><article key={i.id}><Sparkles/><div><b>{i.title}</b><p>{i.recommendation}</p><small>اطمینان {Math.round(i.confidence*100)}٪</small></div></article>)}</div></section></div></div>}

function AdvisorDashboard(){const nav=useNavigate();const {data,isLoading}=useQuery({queryKey:['advisor-dashboard'],queryFn:()=>api<AdvisorData>('/advisors/dashboard')});if(isLoading||!data)return <Loading/>;return <div className="dashboard-page"><Welcome name={data.user.full_name} subtitle="اولویت‌های امروز و وضعیت دانش‌آموزان شما آماده است."/><div className="metric-grid"><Metric icon={Users} label="دانش‌آموز فعال" value={`${data.students.length} نفر`} tone="purple"/><Metric icon={Bell} label="هشدار نیازمند بررسی" value={`${data.alerts} مورد`} tone="orange"/><Metric icon={BrainCircuit} label="پیشنهاد AI" value={`${data.pending_insights} مورد`} tone="blue"/><Metric icon={ClipboardCheck} label="برنامه این هفته" value={`${data.weekly_plans} برنامه`} tone="green"/></div><div className="dashboard-grid"><section className="panel span-2"><PanelTitle title="صف پیگیری دانش‌آموزان" action="همه دانش‌آموزان"/><div className="student-table"><div className="table-head"><span>دانش‌آموز</span><span>ریسک</span><span>پیشرفت</span><span>اقدام</span></div>{data.students.map((s,i)=><div className="table-row" key={s.id}><span><i className={`avatar av-${i}`}>{s.full_name[0]}</i><b>{s.full_name}</b></span><span className={`risk ${s.risk==='بالا'?'high':''}`}>{s.risk}</span><span><i className="table-progress"><b style={{width:`${s.progress}%`}}/></i>{s.progress}٪</span><button onClick={()=>nav(`/app/advisor/students/${s.id}/report`)}>مشاهده پرونده <ChevronLeft/></button></div>)}</div></section><section className="panel"><PanelTitle title="اولویت امروز"/><div className="priority-list"><p><span>۱</span><b>بررسی هشدار افت مطالعه</b><small>پارسا رضایی · ۲ ساعت پیش</small></p><p><span>۲</span><b>تایید پیشنهاد برنامه</b><small>نسخه هوشمند آماده بازبینی</small></p><p><span>۳</span><b>پاسخ به پیام جدید</b><small>میانگین پاسخ‌گویی: ۱۲ دقیقه</small></p></div></section><section className="panel span-2"><PanelTitle title="روند پیشرفت گروه" action="گزارش پرتفوی"/><ChartCard/></section><section className="panel"><PanelTitle title="کنترل هوشمند"/><div className="ai-control"><div className="ai-orb"><BrainCircuit/></div><h3>۳ پیشنهاد آماده بازبینی</h3><p>شواهد و سطح اطمینان هر پیشنهاد قبل از انتشار قابل مشاهده است.</p><button className="btn btn-primary">بازبینی پیشنهادها</button></div></section></div></div>}

function AdminDashboard({user}:{user:User}){const {data,isLoading}=useQuery({queryKey:['admin-dashboard'],queryFn:()=>api<AdminData>('/admin/dashboard')});if(isLoading||!data)return <Loading/>;const c=data.counts;return <div className="dashboard-page"><Welcome name={user.full_name} subtitle="سلامت سامانه، کاربران و عملیات حساس در یک نگاه."/><div className="metric-grid"><Metric icon={Users} label="کل کاربران" value={`${c.users||0}`} tone="purple"/><Metric icon={GraduationCap} label="دانش‌آموزان" value={`${c.students||0}`} tone="blue"/><Metric icon={FileQuestion} label="بانک سؤال" value={`${c.questions||0}`} tone="orange"/><Metric icon={ShieldCheck} label="رویداد ممیزی" value={`${c.audits||0}`} tone="green"/></div><div className="dashboard-grid"><section className="panel span-2"><PanelTitle title="وضعیت عملیاتی" action="مشاهده جزئیات"/><div className="ops-grid"><article><span className="service-ok"/><b>API و دیتابیس</b><p>{data.service.status} · {data.service.database}</p></article><article><span className="service-ok"/><b>پردازش‌های زمان‌بندی</b><p>{data.service.jobs} · بدون خطای معوق</p></article><article><span className="service-ok warning"/><b>یکپارچه‌سازی‌ها</b><p>AI و پرداخت در حالت Mock</p></article></div><ChartCard/></section><section className="panel"><PanelTitle title="دسترسی سریع"/><div className="admin-actions"><button><Users/>مدیریت کاربران<ChevronLeft/></button><button><FileQuestion/>بانک سؤال<ChevronLeft/></button><button><CreditCard/>امور مالی<ChevronLeft/></button><button><ShieldCheck/>گزارش ممیزی<ChevronLeft/></button></div></section><section className="panel span-3"><PanelTitle title="ماژول‌های سامانه"/><div className="module-grid">{['هویت و دسترسی','دانش‌آموز','میزکار مشاور','برنامه‌ریزی','ارتباطات','بانک سؤال','آزمون آنلاین','تحلیل و گزارش','هوش مصنوعی','اشتراک و پرداخت'].map((m,i)=><article key={m}><span>{i+1}</span><b>{m}</b><small>فعال و متصل</small></article>)}</div></section></div></div>}

function Welcome({name,subtitle}:{name:string;subtitle:string}){return <div className="dashboard-welcome"><div><p>سلام، {name.split(' ')[0]} عزیز 👋</p><h1>روز خوبی برای پیشرفت است</h1><span>{subtitle}</span></div><div className="date-chip">شنبه، ۲۴ مرداد ۱۴۰۵</div></div>}
function Metric({icon:Icon,label,value,tone}:{icon:typeof Home;label:string;value:string;tone:string}){return <article className="metric"><span className={tone}><Icon/></span><div><small>{label}</small><b>{value}</b></div><TrendingUp className="metric-trend"/></article>}
function PanelTitle({title,action}:{title:string;action?:string}){return <div className="panel-title"><h2>{title}</h2>{action&&<button>{action}<ChevronLeft/></button>}</div>}
function Loading(){return <div className="screen-loader"><span className="brand-mark"/> در حال دریافت اطلاعات...</div>}
